export default{
    name:"project",
    title:"project",
    type:"document",
    fields:[
        {
            name:"image",
            title:"Image",
            type:"image",
            options:{
                hotspot:"true"
            }
        },
        {
            name:"name",
            title:"Name",
            type:"string",
        },
        {
            name:"description",
            title:"Description",
            type:"string",
        },
        {
            name:"link",
            title:"Link",
            type:"url",
        },
        {
            name:"githubLink",
            title:"GithubLink",
            type:"url",
        },
        {
            name:"skill",
            title:"Skill",
            type:"array",
            of:[
                {type:"string"}
            ]
        },
        {
            name:"framework",
            title:"Framework",
            type:"boolean"
        },


    ]
}